
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
      debian_chroot=$(cat /etc/debian_chroot)
    fi
#SVN EDITOR
SVN_EDITOR=vi
export SVN_EDITOR

#PATHS
PYNE_PATH="/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/"
export PYNE_PATH

HDF5_DIR="/opt/local"
export HDF5_DIR
HDF5_ROOT="/opt/local/lib"
export HDF5_ROOT

LD_LIBRARY_PATH="/usr/local:/opt/local:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

DYLD_FALLBACK_LIBRARY_PATH="/opt/local/lib:/opt/local"
export DYLD_FALLBACK_LIBRARY_PATH

PATH="${HDF5_DIR}:/opt/local:/opt/local/bin:/usr/local/bin:/usr/local/sbin:/opt/local/include:/opt/local/lib:${PATH}"
export PATH

PYTHONPATH="${PYNE_PATH}:/Users/khuff/repos/cyder/output/:/Users/khuff/repos/cyder/input/:${PYTHONPATH}"
export PYTHONPATH

DATAPATH="/Users/khuff/serpent/xsdata:${DATAPATH}"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
      . ~/.bash_aliases
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
fi

export CLICOLOR
export LSCOLOR

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt 
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
    else
  color_prompt=
    fi
fi

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

if [ "$color_prompt" = yes ]; then
    PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$(parse_git_branch) $ "
else
    PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$(parse_git_branch) $"
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

umask 002

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH

INPUTRC="/Users/khuff/.inputrc"
export INPUTRC
